### ISSUE TITLE
Graph view causes out of memory crash on 100_strains test data

### ISSUE THREAD

**Issue by jorenham** [ProgrammingLife2015/LifeTiles#88]
Parsing the 100_strains data set causes a stack-overflow. This can possible be resolved by https://github.com/ProgrammingLife5/LifeTiles/issues/22 .

**Comment by rutgervandenberg** [comment]
The parser doesnt crash on 38 strains. The SequenceGenerator does. Since #68 requires the sequenceGenerator to be integrated into the parser, debugging the sequencegenerator right now is probably not worth it. 

The parser DOES however crash on 100 strains. Or, more specifically, the (internal) graph causes a stack overflow.
